apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: genuc-backend-pdb
  namespace: genuc
  labels:
    app.kubernetes.io/name: genuc
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: genuc-frontend-pdb
  namespace: genuc
  labels:
    app.kubernetes.io/name: genuc
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
