package cd.genuc.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;

/**
 * ReportGenerateDto - Request DTO for report generation
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReportGenerateDto {
    @NotNull(message = "University ID is required")
    private Long universiteId;

    @NotNull(message = "Report date is required")
    private LocalDate reportDate;

    @NotNull(message = "Generated by user ID is required")
    private Long generatedBy;
}
