-- V14 — Tables absentes du jeu de migrations.
--
-- Les entités DocumentAnalyse, MigrationImport et MigrationLigne existaient dans
-- le modèle sans migration correspondante. Le profil prod (ddl-auto=validate)
-- échouait donc au démarrage :
--   Schema-validation: missing table [documents_analyse]
-- En dev le problème restait invisible : ddl-auto=update fabrique le schéma.
--
-- DDL relevé sur un schéma produit par Hibernate lui-même, pour que la
-- validation passe au caractère près. Les contraintes générées portaient des
-- noms aléatoires (ukhmu0aeo2oe56..., fk6thijq4rj7yla8...) ; elles sont
-- renommées ici de façon lisible et stable — Hibernate valide la structure,
-- pas le nom des contraintes.

-- ─── Analyse automatique des pièces d'un dossier d'inscription ───────────
CREATE TABLE documents_analyse (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alertes       text,
    cle_document  varchar(255),
    cree_le       timestamp(6),
    dossier_id    bigint,
    score_qualite integer,
    sha256        varchar(64),
    type_detecte  varchar(255),
    CONSTRAINT uk_documents_analyse_dossier_cle UNIQUE (dossier_id, cle_document)
);

-- ─── Imports en masse (CSV / Excel) ──────────────────────────────────────
CREATE TABLE migrations_import (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annee_academique       varchar(255),
    colonnes_json          text,
    cree_le                timestamp(6),
    cree_par               varchar(255),
    etape                  integer NOT NULL,
    lignes_erreur          integer NOT NULL,
    lignes_ignorees        integer NOT NULL,
    lignes_importees       integer NOT NULL,
    maj_le                 timestamp(6),
    mapping_json           text,
    nom                    varchar(255) NOT NULL,
    nom_fichier_original   varchar(255),
    options_json           text,
    progression            integer NOT NULL,
    stats_json             text,
    statut                 varchar(255),
    total_lignes           integer NOT NULL,
    type_fichier           varchar(255),
    universite_id          bigint NOT NULL,
    CONSTRAINT fk_migrations_import_universite
        FOREIGN KEY (universite_id) REFERENCES universites (id),
    CONSTRAINT migrations_import_statut_check CHECK (statut IN (
        'EN_ATTENTE', 'ANALYSE', 'MAPPING', 'VERIFICATION', 'SIMULATION',
        'EN_COURS', 'PAUSE', 'ERREURS', 'TERMINE', 'ANNULE')),
    CONSTRAINT migrations_import_type_fichier_check CHECK (type_fichier IN ('CSV', 'EXCEL'))
);

-- ─── Lignes d'un import, avec leur état de traitement ────────────────────
CREATE TABLE migrations_lignes (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action         varchar(255),
    donnees_json   text,
    erreurs_json   text,
    etudiant_id    bigint,
    inscription_id bigint,
    numero_ligne   integer NOT NULL,
    paiement_id    bigint,
    statut         varchar(255),
    migration_id   bigint NOT NULL,
    CONSTRAINT fk_migrations_lignes_migration
        FOREIGN KEY (migration_id) REFERENCES migrations_import (id),
    CONSTRAINT migrations_lignes_action_check CHECK (action IN (
        'CREER', 'METTRE_A_JOUR', 'IGNORER')),
    CONSTRAINT migrations_lignes_statut_check CHECK (statut IN (
        'VALIDE', 'AVERTISSEMENT', 'ERREUR', 'IMPORTEE', 'IGNOREE'))
);

CREATE INDEX idx_migl_migration ON migrations_lignes (migration_id);
CREATE INDEX idx_migl_statut    ON migrations_lignes (statut);
